//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOC2022.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AOC2022.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 261
        ///1773
        ///1839
        ///1551
        ///1781
        ///1276
        ///1372
        ///1668
        ///1823
        ///1870
        ///1672
        ///1821
        ///1327
        ///1902
        ///1949
        ///1389
        ///1720
        ///1437
        ///1716
        ///1360
        ///1893
        ///1410
        ///1881
        ///1927
        ///1639
        ///1514
        ///1753
        ///1625
        ///1249
        ///1696
        ///1698
        ///1699
        ///2004
        ///1742
        ///1903
        ///473
        ///1948
        ///1830
        ///1973
        ///2005
        ///1468
        ///1824
        ///1809
        ///1493
        ///2009
        ///1848
        ///1306
        ///1519
        ///1618
        ///1905
        ///1402
        ///1705
        ///1910
        ///1609
        ///1571
        ///1557
        ///1420
        ///608
        ///1471
        ///1383
        ///1442
        ///1447
        ///1985
        ///1486
        ///1629
        ///1450
        ///1767
        ///1407
        ///1626
        ///1623
        ///1467
        ///1224
        ///1269
        ///1325
        ///1674
        ///1945
        ///1733
        ///1913
        ///1451
        ///1853
        ///1875
        ///405
        ///1500
        ///1634
        ///1570
        ///1868
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input01 {
            get {
                return ResourceManager.GetString("Input01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13-16 k: kkkkkgmkbvkkrskhd
        ///5-6 p: qpppvzp
        ///3-4 p: psppxhlfpvkh
        ///3-10 w: wwwwwwwwwwdwww
        ///4-5 r: rcgrrcr
        ///3-4 c: clvccc
        ///1-5 x: xfsfxmctb
        ///9-14 k: kpkmkkckhkkkkvkk
        ///5-6 s: gsfsss
        ///4-8 c: cccdcqdcr
        ///2-5 k: kmkpkkfgkkkkdkkk
        ///9-11 f: pfnsfffwxsn
        ///8-9 w: wjwnwcwxc
        ///7-8 q: rrxhplqs
        ///5-10 n: gpnkqnxnbjzgjnb
        ///18-19 p: fvpkgfkfjgwllqwhrjd
        ///12-13 v: kvvvbmdvvvvvvcvvvv
        ///3-5 m: mdmkmvhszpjcxl
        ///2-7 v: qjmvzdwxc
        ///1-4 b: bbbbbbbb
        ///2-5 c: fzcdccfkcsjhckccrcx
        ///2-10 d: fhdwdbdddrsldrtdjdr
        ///1-7 z: ztszzfzztcqzrz
        ///4-6 j: mmjjj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input02 {
            get {
                return ResourceManager.GetString("Input02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input03 {
            get {
                return ResourceManager.GetString("Input03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input04 {
            get {
                return ResourceManager.GetString("Input04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input05 {
            get {
                return ResourceManager.GetString("Input05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input06 {
            get {
                return ResourceManager.GetString("Input06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input07 {
            get {
                return ResourceManager.GetString("Input07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input08 {
            get {
                return ResourceManager.GetString("Input08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input09 {
            get {
                return ResourceManager.GetString("Input09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input10 {
            get {
                return ResourceManager.GetString("Input10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input11 {
            get {
                return ResourceManager.GetString("Input11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input12 {
            get {
                return ResourceManager.GetString("Input12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input13 {
            get {
                return ResourceManager.GetString("Input13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input14 {
            get {
                return ResourceManager.GetString("Input14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input15 {
            get {
                return ResourceManager.GetString("Input15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input16 {
            get {
                return ResourceManager.GetString("Input16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input17 {
            get {
                return ResourceManager.GetString("Input17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input18 {
            get {
                return ResourceManager.GetString("Input18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input19 {
            get {
                return ResourceManager.GetString("Input19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input20 {
            get {
                return ResourceManager.GetString("Input20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input21 {
            get {
                return ResourceManager.GetString("Input21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input22 {
            get {
                return ResourceManager.GetString("Input22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input23 {
            get {
                return ResourceManager.GetString("Input23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input24 {
            get {
                return ResourceManager.GetString("Input24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Input25 {
            get {
                return ResourceManager.GetString("Input25", resourceCulture);
            }
        }
    }
}
